# Generated by Django 3.0.4 on 2020-03-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='cat',
        ),
    ]
