# Generated by Django 3.0.4 on 2020-03-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200320_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat',
            new_name='category',
        ),
    ]
